title: Analythium
description: Cloud-native analytics powered by open source
# url: https://analythium.io
# baseurl: ""
url: https://hub.analythium.io
baseurl: "/analythium-website"
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--truncate-->
timezone: UTC
collections:
  projects:
    output: true
    permalink: /projects/:name/
